name: "MochaUI"

version: "1.1-dev"

exports: "mochaui.js"

web: "[mui.github.io/mochaui](https://mui.github.io/mochaui/)"

description: "MochaUI, A web applications user interface library"

license: "[MIT License](https://mui.github.io/mochaui/MIT-LICENSE.txt)"

copyright: "&copy; [AUTHORS.txt](https://mui.github.io/mochaui/AUTHORS.txt)"

authors:
  - "[Chris Doty](http://polaropposite.com/)"
  - "[Greg Houston](http://greghoustondesign.com/)"
  - "Scott F. Frederick"
  - "Joel Lindau"
  - "Harry Roberts"

sources:
  - "Source/Core/core.js"
  - "Source/Core/create.js"
  - "Source/Core/require.js"
  - "Source/Core/canvas.js"
  - "Source/Core/content.js"
  - "Source/Core/persist.js"
  - "Source/Core/themes.js"

  
